import {initCloud,saveCloud,cloudReady} from './cloud-auth.js';
import {journeyProgress,renderJourneyProgress,renderStoryThread} from './journey-progress.js';
import {installChoiceKeyboard,choiceHint} from './choice-keyboard.js';
import {createImmersion} from './immersive.js';
import {createEngine} from './engine.js';
import {regions,companions,chapterStory} from './story.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='qianzai-odyssey-v1'+(new URLSearchParams(location.search).has('test')?'-test':'');
let works,curriculum,engine,state,region=0,selected=0,bagLimit=30,bagChapter=null,toastTimer,pendingImport;
const lesson=$('#lesson');
const immersion=createImmersion({regions,companions,kind:'literature'});
const scene=(r)=>`background-image:url('assets/${r.asset}.webp');background-position:${r.position}`;
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
let storageBlocked=false;
function persist(){if(!cloudReady())return false;if(storageBlocked)return false;try{localStorage.setItem(KEY,JSON.stringify(state));$('#storage-warning').hidden=true;saveCloud(state);return true;}catch{$('#storage-warning').hidden=false;$('#storage-warning').textContent='目前無法儲存至瀏覽器。進度暫留這個頁面，關閉前請到成長手札匯出備份。';return false;}}
function show(view){$$('.view').forEach(el=>el.hidden=el.id!==`view-${view}`);$$('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===view);el.setAttribute('aria-current',el.dataset.view===view?'page':'false');});history.replaceState(null,'',`#${view}`);if(view==='bag')renderBag();if(view==='journal')renderJournal();if(view==='story')renderStories();window.scrollTo({top:0,behavior:'instant'});}
function statHTML(){const s=engine.stats(state);return [[s.learned,'已收集文珠','題','◈'],[s.xp,'行旅經驗','XP','✧'],[s.chapters,'已過小關','／100','⌁'],[s.mastered,'已熟練文珠','題','❀']].map(([n,t,u,icon])=>`<div class="stat"><span class="stat-icon" aria-hidden="true">${icon}</span><div><small>${t}</small><b>${n.toLocaleString()}</b><em>${u}</em></div></div>`).join('');}
function render(){
 $('#stats').innerHTML=statHTML();$('#bag-count').textContent=engine.stats(state).learned;$('#header-xp').textContent=`${engine.stats(state).learned.toLocaleString()} 文珠`;
 $('#companion').value=state.companion;$('#companion-mobile').value=state.companion;$('#companion-line').textContent=companions.find(c=>c.id===state.companion).line;$('.portrait').className=`portrait ${state.companion}`;const portraitIndex=companions.findIndex(c=>c.id===state.companion);$('.portrait').style.backgroundPosition=`${portraitIndex%5*25}% ${portraitIndex<5?0:100}%`;
 $('#batch').value=state.batch;$('#due-label').textContent=`${engine.due(state).length} 題等你重逢。新任務會先安排最多 10 題到期複習。`;
 $('#review').disabled=engine.due(state).length===0;$('#resume').hidden=!state.draft||state.draft.phase==='done';
 $('#hero-start').textContent=state.draft&&state.draft.phase!=='done'?'接續未完成的旅程 →':engine.current(state)===100?'已讀完十朝・查看書卷 →':'展開今日旅程 →';
 $('#region-tabs').innerHTML=regions.map((r,i)=>`<button class="region-tab ${i===region?'active':''}" data-region="${i}" aria-pressed="${i===region}"><small>${String(i+1).padStart(2,'0')}</small>${r.name}</button>`).join('');
 $$('[data-region]').forEach(b=>b.onclick=()=>{region=Number(b.dataset.region);const current=engine.current(state);selected=current>=region*10&&current<region*10+10?current:region*10;render();immersion.center();});
 const r=regions[region];$('#region-tag').textContent=r.tag;$('#map-name').textContent=r.name;$('#landscape').setAttribute('style',scene(r));$('#landscape').setAttribute('aria-label',`${r.name}旅程地圖`);
 const points=[[10,71],[19,48],[31,53],[43,40],[57,28],[80,20],[87,49],[70,64],[51,79],[28,86]];
 $('#map-nodes').innerHTML=points.map(([x,y],i)=>{const n=region*10+i,done=engine.complete(state,n),current=engine.current(state);return `<button class="map-node ${n===current?'current':done?'done':'locked'} ${n===selected?'selected':''}" data-chapter="${n}" style="left:${x}%;top:${y}%" aria-label="第${n+1}章 ${r.steps[i]}，${done?'已完成':n===current?'當前冒險':'尚未解鎖'}" aria-pressed="${selected===n}"><b>${done?'✓':n+1}</b><span>${r.steps[i]}</span></button>`;}).join('');
 $$('[data-chapter]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.chapter);render();immersion.openChapter();});renderChapter();immersion.update(region,selected);$('#scene-progress').innerHTML=renderJourneyProgress(journeyProgress(engine,state,regions,selected),{compact:true});$('#picker-progress').innerHTML=renderJourneyProgress(journeyProgress(engine,state,regions,selected));
}
function renderChapter(){const r=regions[Math.floor(selected/10)],story=chapterStory(selected,state.choices[Math.floor(selected/10)]),c=engine.chapters[selected],count=c.ids.filter(id=>state.learned[id]).length,current=engine.current(state),locked=selected>current,done=engine.complete(state,selected);
 $('#chapter-card').innerHTML=`<p class="eyebrow">${locked?'前方的風景':done?'已留下你的足跡':'正在等你出發'}・第 ${selected%10+1}／10 小關</p><h3>${story.title}</h3><p class="story-text">${story.text}</p><p class="request">${r.request}</p>${renderJourneyProgress(journeyProgress(engine,state,regions,selected))}${renderStoryThread(story,{done,remaining:c.ids.length-count})}<p class="chapter-authors">本小關選讀：${esc(curriculum[selected].authors.join("、"))}</p><div class="chapter-meta"><span>本小關文珠 ${count}／${c.ids.length}</span><span>${esc(curriculum[selected].focus)}</span></div><div class="bar"><i style="width:${count/c.ids.length*100}%"></i></div><button class="primary" id="chapter-start" ${locked?'disabled':''}>${locked?'完成前章後解鎖':done?'打開本小關文珠':state.draft&&state.draft.phase!=='done'?'接續未完成練習':'接受任務・拾字出發'} <span>→</span></button><p class="hint">${locked?'可以先看風景，學習會依序前進。':done?story.ending:'讀懂原句 → 面對試煉 → 帶回文珠'}</p><button class="text-button" id="chapter-preview">試讀本小關原文・不計進度 ↗</button>`;
 $('#chapter-preview').onclick=()=>{immersion.closeChapter();preview(selected);};
 $('#chapter-start').onclick=()=>{immersion.closeChapter();if(done){bagChapter=selected;$('#search').value='';$('#bag-filter').value='all';show('bag');}else begin('new');};}
function begin(kind){
 if(storageBlocked){toast('請先處理存檔讀取問題，避免覆蓋原進度。');return;}
 if(kind==='new'&&engine.current(state)===100){show('story');return;}
 if(state.draft&&state.draft.phase!=='done'){lesson.showModal();renderLesson();return;}
 const rIndex=Math.floor(Math.min(engine.current(state),99)/10),r=regions[rIndex];
 if(kind==='new'&&state.choices[rIndex]===undefined){
  $('#lesson-body').innerHTML=`<div class="lesson-head"><span class="lesson-phase">${r.tag}</span><span>接受召喚</span></div><div class="story-scene" style="${scene(r)};margin-top:18px;border-radius:6px" role="img" aria-label="${r.name}水墨地景"></div><h2 id="lesson-title" class="lesson-title">${r.subtitle}</h2><p>${r.intro}</p><p class="source">這一站，你想怎麼幫忙？選擇會留在書卷裡，兩條路都要完成詩文續句練習。</p><div class="dialog-actions">${r.choices.map((c,i)=>`<button class="${i===0?'primary':'secondary'}" data-opening-choice="${i}">${c}</button>`).join('')}</div>`;
  $$('[data-opening-choice]').forEach(b=>b.onclick=()=>{state.choices[rIndex]=Number(b.dataset.openingChoice);persist();launch(kind);});lesson.showModal();return;
 }
 launch(kind);
}
function launch(kind){if(!engine.begin(state,kind)){toast('目前沒有到期文珠，晚一點再來重逢。');return;}persist();if(!lesson.open)lesson.showModal();renderLesson();render();}
function correctExplain(q){return Array.isArray(q.explain)?q.explain[q.options.indexOf(q.answer)]:q.explain;}
function renderLesson(){
 const d=state.draft;if(!d){lesson.close();return;}
 const r=regions[Math.floor(d.chapter/10)];
 if(d.phase==='done'){
  const story=chapterStory(d.chapter,state.choices[Math.floor(d.chapter/10)]),done=engine.complete(state,d.chapter);
  $('#lesson-body').innerHTML=`<div class="result"><div class="result-seal">${d.kind==='review'?'重逢':'拾字'}</div><h2 id="lesson-title">${d.kind==='review'?'舊句，又熟悉了一點。':done?'這個小關，完成了！':'這一批完成，小關還在前進。'}</h2><p>${d.earned?`收集 ${d.earned/10} 顆文珠，獲得 ${d.earned} XP。`:'複習已記錄，不重複計入新題與 XP。'}</p>${renderJourneyProgress(journeyProgress(engine,state,regions,d.chapter))}${renderStoryThread(story,{done,review:d.kind==='review',remaining:journeyProgress(engine,state,regions,d.chapter).remaining})}${done&&d.chapter%10===9?`<p class="source">${story.echo}</p>`:''}<button id="continue-batch" class="primary">${done?'前往下一段故事':'繼續這個小關'} →</button><button id="finish" class="secondary">回到故事場景・稍作休息</button></div>`;
  $('#continue-batch').onclick=()=>{state.draft=null;persist();lesson.close();selected=Math.min(engine.current(state),engine.chapters.length-1);region=Math.floor(selected/10);render();if(done||d.kind==='review'){immersion.enter();}else launch('new');};
  $('#finish').onclick=()=>{state.draft=null;persist();selected=Math.min(engine.current(state),99);region=Math.floor(selected/10);lesson.close();render();immersion.enter();};return;
 }
 const q=engine.question(state),learning=d.phase==='learn',feedback=d.feedback,recall=!learning&&engine.mode(state)==='recall';
 const label={learn:'導師指引・讀懂原句',quiz:'面對試煉・取回文珠',review:'舊句重逢・行前複習'}[d.phase];
 const options=learning?'':recall?`<form id="recall-form" class="question-input"><input id="recall-input" aria-label="輸入${'缺少的下句'}" placeholder="${'輸入原文下句，不需標點'}" autocomplete="off" autocapitalize="off" ${feedback?'disabled':''} value="${feedback?esc(feedback.value):''}"><button class="primary" ${feedback?'disabled':''}>確認答案</button></form>`:`<p class="source">${choiceHint}</p><div class="options" data-quiz-options>${q.options.map((o,i)=>`<button class="option ${feedback&&(o===q.answer)?'correct':feedback&&o===feedback.value?'wrong':''}" data-quiz-choice data-answer="${i}" ${feedback?'disabled':''}><small>${"ABCD"[i]}</small> ${esc(o)}</button>`).join('')}</div>`;
 let explanation='';if(learning)explanation=`<div class="flash-answer">${esc(q.answer)}</div><div class="explanation">${esc(correctExplain(q))}</div>`;
 if(feedback){const index=q.options.indexOf(feedback.value),detail=feedback.correct?correctExplain(q):Array.isArray(q.explain)&&index>=0?q.explain[index]:correctExplain(q);explanation=`<div class="explanation ${feedback.correct?'':'wrong'}" role="status"><b>${feedback.correct?'答對了，這顆文珠亮起來了。':'先看清楚，再給自己一次機會。'}</b><p>正確答案：${esc(q.answer)}</p>${esc(detail)}${feedback.correct?'':'<p>這題已排到後面，讀完解析後再試一次。</p>'}</div>`;}
 $('#lesson-body').innerHTML=`${renderJourneyProgress(journeyProgress(engine,state,regions,d.chapter))}<p class="source">本批新題 ${d.ids.length} 題 · ${d.phase==='review'?'先複習舊題，再繼續新題；複習不增加本小關進度。':'先認識 → 再答題 → 整批收集。'}</p><div class="lesson-head"><span class="lesson-phase">${label}</span><span>${learning?`詞卡 ${d.pos+1}／${d.queue.length}`:`待練 ${new Set(d.queue.slice(d.pos)).size} 題（含重練）`}</span></div><div class="bar" style="margin-top:12px"><i style="width:${(d.pos+1)/d.queue.length*100}%"></i></div><p class="source">第 ${d.chapter%10+1} 小關・${r.steps[d.chapter%10]}　${q.eraName}／${q.genre}／${q.famous?"名句選讀":"延伸詩文"}</p><h2 class="question-text" id="lesson-title">${esc(q.question)}</h2>${options}${explanation}<div id="hint-box" class="source">${d.hints[q.id]&&!learning?`提示已使用：答案從「${esc([...q.answer][0])}」開始。本次不計首次獨立答對。`:''}</div><p class="source">${q.eraName}・${esc(q.source)}${q.note?`<br>${esc(q.note)}`:''}</p>${learning||feedback?`<button class="text-button" id="read-work">閱讀完整原文 ↗</button>`:""}<div class="lesson-bottom">${learning?'<small>先讀懂，再試著不看答案回想。</small>':feedback?'<small>願意訂正，就是往前走。</small>':'<button class="text-button" id="hint">給我一點提示</button>'}${learning||feedback?`<button class="primary" id="next-question">${learning?'我記好了，下一步':'繼續旅程'} →</button>`:'<small>答錯不扣分，完成整批才收進行囊。</small>'}</div>`;
 if($('#read-work'))$('#read-work').onclick=()=>readWork(q.workId);
 $$('[data-answer]').forEach(b=>b.onclick=()=>submit(q.options[Number(b.dataset.answer)]));
 if($('#recall-form'))$('#recall-form').onsubmit=e=>{e.preventDefault();const value=$('#recall-input').value.trim();if(value)submit(value);else toast('先輸入答案，再確認。');};
 if($('#hint'))$('#hint').onclick=()=>{engine.hint(state);persist();$('#hint-box').textContent=`先看上下文與句意。答案從「${[...q.answer][0]}」開始；本次標記為有提示。`;};
 if($('#next-question'))$('#next-question').onclick=()=>{engine.next(state);persist();renderLesson();render();lesson.scrollTop=0;$('#lesson-title')?.setAttribute('tabindex','-1');$('#lesson-title')?.focus({preventScroll:true});};
}
function submit(value){const result=engine.answer(state,value);if(!result)return;if(result.correct)engine.next(state);persist();renderLesson();render();lesson.scrollTop=0;const focus=result.correct?$('#lesson-title'):$('#next-question');focus?.setAttribute('tabindex','-1');focus?.focus({preventScroll:true});}
function renderBag(){const filter=$('#bag-filter').value,query=$('#search').value.trim(),now=Date.now();let questions=engine.bank.filter(q=>state.learned[q.id]);if(bagChapter!==null)questions=questions.filter(q=>engine.chapters[bagChapter].ids.includes(q.id));questions=questions.filter(q=>(!query||[q.question,q.answer,q.author,q.work].join(' ').includes(query))&&(filter==='all'||filter==='due'&&state.learned[q.id].due<=now||filter==='mastered'&&state.learned[q.id].days.length>=3&&state.learned[q.id].recall>0||filter===q.genre));$('#bag-status').textContent=`${bagChapter!==null?`第 ${bagChapter+1} 章・`:''}找到 ${questions.length} 題，顯示 ${Math.min(questions.length,bagLimit)} 題。`;
 $('#bag-list').innerHTML=questions.length?questions.slice(0,bagLimit).map(q=>`<button class="bag-item" data-word="${esc(q.id)}"><small>${q.genre}・${q.level}<span class="label">${state.learned[q.id].due<=now?'等待複習':'已收集'}</span></small><p>${esc(q.question)}</p><strong>${esc(q.answer)}</strong><small style="display:block;margin-top:10px">點開看解析與複習紀錄 →</small></button>`).join(''):'<div class="empty">行囊裡暫時沒有符合的文珠。<br>去地圖完成一批練習，或換個搜尋條件。</div>';
 $('#more').hidden=questions.length<=bagLimit;$$('[data-word]').forEach(b=>b.onclick=()=>{const q=engine.byId.get(b.dataset.word),r=state.learned[q.id];$('#info-body').innerHTML=`<h2 id="info-title">${esc(q.question)}</h2><div class="flash-answer">${esc(q.answer)}</div><p>${esc(q.explain)}</p><button class="text-button" id="bag-read-work">閱讀完整原文 ↗</button><p class="source">${esc(q.source)}<br>完成複習 ${r.reviews} 次・不同日期首次無提示答對 ${r.days.length} 天・輸入回憶 ${r.recall} 次<br>下次複習：${new Date(r.due).toLocaleString('zh-TW')}</p>`;$('#info').showModal();$('#bag-read-work').onclick=()=>readWork(q.workId);});}
function renderJournal(){$('#journal-stats').innerHTML=statHTML();$('#history').innerHTML=state.history.length?[...state.history].reverse().slice(0,100).map(h=>`<article class="history-row"><time>${new Date(h.at).toLocaleString('zh-TW',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</time><div><h3>${regions[Math.floor(h.chapter/10)].name}・${chapterStory(h.chapter).title}</h3><p>帶回 ${h.ids.length} 顆文珠</p></div><b>+${h.ids.length*10} XP</b></article>`).join(''):'<div class="empty">第一頁還空著。去完成一段屬於你的旅程吧。</div>';}
function renderStories(){const current=engine.current(state);$('#story-gallery').innerHTML=regions.map((r,i)=>{const open=current>=i*10,complete=Array.from({length:10},(_,j)=>engine.complete(state,i*10+j)).every(Boolean),choice=state.choices[i];return `<article class="story-card"><div class="story-scene" style="${scene(r)}" role="img" aria-label="${r.name}水墨地景"><span>${r.name}</span></div><div><div class="mentor" style="background-position:${i%5*25}% ${i<5?0:100}%" role="img" aria-label="${r.mentor.name}兩頭身水墨人物"></div><p class="eyebrow">${r.tag}・${r.mentor.name}</p><h3>${r.subtitle}</h3><p>${r.intro}</p><p>${open?r.request:'完成前一站後，這裡的故事將等待你續寫。'}</p>${open?`<div>${r.choices.map((c,j)=>`<button class="choice ${choice===j?'chosen':''}" data-choice-region="${i}" data-choice-value="${j}" ${choice!==undefined?'disabled':''}>${choice===j?'✓ ':''}${c}</button>`).join('')}</div>${choice!==undefined?`<p>${r.echo[choice]}</p>`:''}`:''}${complete?`<p>${r.ending}</p>`:''}<span class="stamp ${complete?'':'pending'}">${complete?r.seal+'・已修復':'印記待點亮'}</span></div></article>`;}).join('');$$('[data-choice-region]').forEach(b=>b.onclick=()=>{state.choices[b.dataset.choiceRegion]=Number(b.dataset.choiceValue);persist();renderStories();renderChapter();});}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`千載字旅-${new Date().toLocaleDateString('sv-SE')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('旅程備份已送至瀏覽器下載。');}
function preview(chapter){const c=engine.chapters[chapter],r=regions[Math.floor(chapter/10)];$('#info-body').innerHTML=`<h2 id="info-title">${r.name}・${r.steps[chapter%10]}</h2><p class="source">自由試讀前 5 段原文，不計入學習進度。正式旅程由先秦依序前進。</p>${c.ids.slice(0,5).map(id=>{const q=engine.byId.get(id);return `<article class="preview-quote"><p>${esc(q.quote)}</p><small>${esc(q.author)}〈${esc(q.work)}〉・${q.genre}</small><button class="text-button" data-read="${q.workId}">展開原文 ↗</button></article>`;}).join('')}`;$('#info').showModal();$$('[data-read]').forEach(b=>b.onclick=()=>readWork(b.dataset.read));}
function readWork(id){const w=works[id];$('#info-body').innerHTML=`<p class="eyebrow">${regions[w.era].name}・${esc(w.genre)}</p><h2 id="info-title">${esc(w.title)}</h2><p>${esc(w.author)}</p><div class="original-text">${esc(w.content)}</div><p class="source">來源標記：${esc(w.sourceDynasty)}。本站按文學分期編卷；原文已轉為繁體，移除括注，標點可能與其他版本不同。</p><a class="text-button" href="${esc(w.sourceURL)}" target="_blank" rel="noopener noreferrer">核對固定版本來源 ↗</a>`;if(!$('#info').open)$('#info').showModal();$('#info').scrollTop=0;}
function about(){$('#info-body').innerHTML='<h2 id="info-title">一卷千秋，萬句生光</h2><p>《千載字旅》以十個朝代、百個小章串起詩文學習。你是「補卷人」，與歷代文人一起修復失落的千載書卷。水墨 Q 版人物以頭與身體 1:1 的兩頭身為設計設定，插畫由 AI 生成；角色對話與任務故事均為原創虛構，不是歷史人物原話。</p><h3>萬題從哪裡來？</h3><p>第一版含 10,000 段不重複原文，取自數千篇古代作品，包含經典名句與延伸詩文，不代表每一段都是廣為流傳的名言。名句優先是編排訊號，並非官方難度分級。每題均保留作者、篇名與原文，附固定版本來源連結。</p><p>原文取自 chinese-gushiwen 與 poetry-source 公開數位轉錄，使用 OpenCC 轉為繁體。僅使用古代原文，未搬用現代翻譯、賞析與人物畫像。題目是依原文製作的續句練習，干擾選項來自同卷其他句子。原文對照不是逐題人工校勘；遇到異文，請核對指定來源，課堂可再參照教材版本。</p><h3>十朝如何分卷？</h3><p>先秦、漢朝、三國、魏晉六朝、隋唐、五代十國、宋、元、明、清，依序各分十章。每章只取該卷題目；宋、元、明、清各自獨立。三國卷採「建安至三國」文學分期，包含東漢末曹操等作家；竹林作家集中於魏晉六朝。漢代劉向編錄的先秦故事歸入漢卷，傳述背景與編者年代另須分辨。</p><h3>怎麼學與保存？</h3><p>每次 3、5 或 10 題，先複習到期題，再讀原句、回答續句。錯題會再次出現；完成整批才增加文珠與經驗值。地圖各章可以自由試讀，不增加通關進度。三個不同日期的到期複習首次無提示答對，並含一次輸入回憶，才列為熟練。</p><p>訪客進度保存在本機瀏覽器；Google 登入後可跨裝置同步進度。可在成長手札匯出與匯入備份；關閉練習後能接續。請勿以遊戲熟練標記代替課堂理解評量。</p>';$('#info').showModal();}
async function init(){try{const responses=await Promise.all(['questions','works','curriculum'].map(async name=>{const response=await fetch(`./data/${name}.json`);if(!response.ok)throw Error('典籍讀取失敗');return response.json();}));works=responses[1];curriculum=responses[2];engine=createEngine(responses[0]);state=engine.fresh();try{const raw=localStorage.getItem(KEY);if(raw)state=engine.load(raw);}catch{storageBlocked=true;$('#storage-warning').hidden=false;$('#storage-warning').innerHTML='原本的旅程無法讀取，已保留原資料並暫停新練習。請匯入有效備份，或先<a id="download-original" href="#">下載原始存檔</a>後再處理。';$('#download-original').onclick=e=>{e.preventDefault();let raw='';try{raw=localStorage.getItem(KEY)||'';}catch{}const a=document.createElement('a'),url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));a.href=url;a.download='千載字旅-原始存檔.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}
 selected=Math.min(engine.current(state),99);region=Math.floor(selected/10);$('#load-status').hidden=true;$('#hero-start').disabled=false;render();
 $$('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='bag'){bagChapter=null;bagLimit=30;}show(b.dataset.view);});$('#hero-start').onclick=()=>{if(state.draft&&state.draft.phase!=='done'){begin('new');return;}selected=Math.min(engine.current(state),99);region=Math.floor(selected/10);render();immersion.enter();};$('#review').onclick=()=>begin('review');$('#resume').onclick=()=>begin('new');$('#batch').onchange=e=>{state.batch=Number(e.target.value);persist();};$('#companion').onchange=$('#companion-mobile').onchange=e=>{state.companion=e.target.value;persist();render();};$('#close-lesson').onclick=()=>lesson.close();lesson.addEventListener('close',()=>{persist();render();});$('#about').onclick=$('#about-footer').onclick=about;$('.brand').onclick=e=>{e.preventDefault();show('journey');};$('#close-info').onclick=()=>$('#info').close();$('#search').oninput=$('#bag-filter').onchange=()=>{bagLimit=30;bagChapter=null;renderBag();};$('#more').onclick=()=>{bagLimit+=30;renderBag();};$('#export').onclick=exportData;
 $('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>6000000)throw Error('備份檔案過大。');pendingImport=engine.load(await file.text());$('#import-summary').textContent=`這份備份包含 ${engine.stats(pendingImport).learned} 題、${engine.stats(pendingImport).chapters} 個完成章節。`;$('#import-confirm').showModal();}catch(error){toast('無法匯入：'+error.message);}finally{e.target.value='';}};$('#cancel-import').onclick=()=>{pendingImport=null;$('#import-confirm').close();};$('#accept-import').onclick=()=>{if(!pendingImport)return;state=pendingImport;pendingImport=null;storageBlocked=false;persist();$('#import-confirm').close();selected=Math.min(engine.current(state),99);region=Math.floor(selected/10);render();renderJournal();toast('旅程已匯入。');};
 window.addEventListener('storage',e=>{if(e.key!==KEY||!cloudReady())return;try{if(!e.newValue)throw Error();state=engine.load(e.newValue);lesson.close();selected=Math.min(engine.current(state),99);region=Math.floor(selected/10);render();renderBag();renderJournal();renderStories();toast('已載入另一分頁的最新進度。');}catch{toast('另一分頁的存檔已變更，請重新載入以確認。');}});
 await initCloud({getSnapshot:()=>state,canLoad:()=>!storageBlocked,notify:toast,applySnapshot:async snapshot=>{pendingImport=null;document.querySelectorAll('dialog[open]:not(#cloud-dialog)').forEach(d=>d.close());state=engine.load(snapshot);localStorage.setItem(KEY,JSON.stringify(state));if(lesson.open)lesson.close();selected=Math.min(engine.current(state),99);region=Math.floor(selected/10);render();renderBag();renderJournal();renderStories();}});
 const view=location.hash.slice(1);show(['journey','bag','journal','story'].includes(view)?view:'journey');
 }catch(error){$('#load-status').textContent=`無法展開書卷：${error.message}。請確認網站伺服器與題庫檔案後重新載入。`;}}
init();

installChoiceKeyboard(document);
