import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createEngine,DAY} from '../engine.js';
import {regions,chapterStory} from '../story.js';
const bank=JSON.parse(readFileSync(new URL('../data/questions.json',import.meta.url))),e=createEngine(bank);
const t=Date.parse('2026-10-04T05:00:00Z');
function finish(s,now=t){let cap=1000;while(s.draft.phase!=='done'&&cap--){if(s.draft.phase!=='learn')e.answer(s,e.question(s).answer,now);e.next(s,now);}assert.ok(cap>0);}
test('all 10000 unique source questions appear once in 100 ordered chapters',()=>{assert.equal(bank.length,10000);assert.equal(e.chapters.length,100);assert.deepEqual(e.chapters.flatMap(c=>c.ids),bank.map(q=>q.id));assert.equal(new Set(bank.map(q=>JSON.stringify([q.question,q.answer]))).size,bank.length);});
test('unfinished cards and wrong answers grant no XP; draft resumes with feedback and retry',()=>{let s=e.fresh();s.batch=3;e.begin(s,'new',t);e.next(s,t);s=e.load(JSON.stringify(s));assert.equal(s.draft.pos,1);assert.equal(e.stats(s).xp,0);while(s.draft.phase==='learn')e.next(s,t);e.answer(s,'wrong',t);assert.equal(s.draft.queue.length,4);const id=e.question(s).id;s=e.load(JSON.stringify(s));assert.equal(s.draft.feedback.correct,false);e.next(s,t);finish(s);assert.equal(e.stats(s).learned,3);assert.equal(e.stats(s).xp,30);assert.equal(s.learned[id].wrong,1);assert.equal(s.learned[id].due,t+600000);e.next(s,t);assert.equal(e.stats(s).xp,30);assert.deepEqual(e.load(JSON.stringify(s)),s);});
test('hint and wrong review do not become independent recall evidence',()=>{const s=e.fresh();s.batch=3;e.begin(s,'new',t);finish(s);e.begin(s,'review',t+DAY);const id=e.question(s).id;e.hint(s);e.answer(s,e.question(s).answer,t+DAY);e.next(s,t+DAY);finish(s,t+DAY);assert.equal(s.learned[id].days.length,0);assert.equal(s.learned[id].recall,0);assert.equal(e.stats(s).xp,30);});
test('mastery requires three due dates and typed recall, never an immediate replay',()=>{const s=e.fresh();s.batch=3;e.begin(s,'new',t);finish(s);let now=t;for(let n=0;n<3;n++){now=Math.max(...Object.values(s.learned).map(r=>r.due));e.begin(s,'review',now);finish(s,now);assert.equal(e.stats(s).mastered,n<2?0:3);}assert.equal(e.begin(s,'review',now),null);assert.equal(e.stats(s).xp,30);assert.deepEqual(e.load(JSON.stringify(s)),s);});
test('backup rejects broken schema, unknown IDs, missing acquisition evidence and impossible progress',()=>{assert.throws(()=>e.load('{}'));let s=e.fresh();s.batch=3;e.begin(s,'new',t);finish(s);const bad=structuredClone(s);bad.learned.unknown=bad.learned[bank[0].id];assert.throws(()=>e.load(bad));const forged=structuredClone(s);forged.history=[];assert.throws(()=>e.load(forged));const missing=structuredClone(s);delete missing.learned[bank[0].id];assert.throws(()=>e.load(missing));});
test('a full 100-chapter journey uses every question and cannot grant duplicate XP',()=>{const s=e.fresh();s.batch=10;let quests=0;while(e.current(s)<100){e.begin(s,'new',t);finish(s,t);quests++;}assert.equal(e.stats(s).learned,10000);assert.equal(e.stats(s).chapters,100);assert.equal(e.stats(s).xp,100000);assert.ok(quests===1000);assert.equal(e.begin(s,'new',t),null);assert.deepEqual(e.load(JSON.stringify(s)),s);});
test('answer feedback preserves the question mode while scheduling next review mode',()=>{const s=e.fresh();s.batch=3;e.begin(s,'new',t);finish(s);e.begin(s,'review',t+DAY);const id=e.question(s).id;assert.equal(e.mode(s),'recognition');e.answer(s,e.question(s).answer,t+DAY);assert.equal(s.learned[id].mode,'recall');assert.equal(e.mode(s),'recognition');assert.equal(e.load(JSON.stringify(s)).draft.feedback.mode,'recognition');});